# install! 'cocoapods', :disable_input_output_paths => true

target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'

  # Pods for iosApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  pod 'composeApp', :path => '../composeApp'
end
